### 1.3.1. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [19]:
import numpy as np

chess = np.zeros((8, 8), dtype=int)
chess[1::2, ::2] = 1
chess[::2, 1::2] = 1
print(chess)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [21]:
import numpy as np

row = np.arange(5)
matrix_5x5 = np.tile(row, (5, 1))
print(matrix_5x5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3. Создать массив 3x3x3 со случайными значениями

In [3]:
import numpy as np

np.random.seed(42)
array_3d = np.random.random((3, 3, 3))
print(array_3d)

[[[0.37454012 0.95071431 0.73199394]
  [0.59865848 0.15601864 0.15599452]
  [0.05808361 0.86617615 0.60111501]]

 [[0.70807258 0.02058449 0.96990985]
  [0.83244264 0.21233911 0.18182497]
  [0.18340451 0.30424224 0.52475643]]

 [[0.43194502 0.29122914 0.61185289]
  [0.13949386 0.29214465 0.36636184]
  [0.45606998 0.78517596 0.19967378]]]


### 1.3.4. Создать матрицу с 0 внутри и 1 на границах

In [4]:
import numpy as np

border = np.ones((5, 5), dtype=int)
border[1:-1, 1:-1] = 0
print(border)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### 1.3.5. Создать массив и отсортировать его по убыванию

In [5]:
import numpy as np

np.random.seed(7)
arr = np.random.randint(0, 100, 10)
print("Исходный массив:", arr)
print("Отсортированный по убыванию:", np.sort(arr)[::-1])

Исходный массив: [47 68 25 67 83 23 92 57 14 23]
Отсортированный по убыванию: [92 83 68 67 57 47 25 23 23 14]


### 1.3.6. Создать матрицу, вывести её форму, размер и размерность

In [6]:
import numpy as np

mat = np.arange(20).reshape(4, 5)
print("Матрица:\n", mat)
print("Форма (shape):", mat.shape)
print("Размер (size):", mat.size)
print("Размерность (ndim):", mat.ndim)

Матрица:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Форма (shape): (4, 5)
Размер (size): 20
Размерность (ndim): 2


### 2.3.1. Найти евклидово расстояние между двумя Series

In [7]:
import pandas as pd
import math

a = pd.Series([1, 2, 3])
b = pd.Series([4, 6, 8])

sum_sq = 0
for x, y in zip(a, b):
    sum_sq += (x - y) ** 2

distance = math.sqrt(sum_sq)
print("Series a:")
print(a)
print("\nSeries b:")
print(b)
print("\nЕвклидово расстояние:", distance)

Series a:
0    1
1    2
2    3
dtype: int64

Series b:
0    4
1    6
2    8
dtype: int64

Евклидово расстояние: 7.0710678118654755


### 2.3.2. Загрузить CSV-файл по ссылке и сформировать DataFrame

В качестве примера используется открытый CSV-файл `tips.csv`. Для выполнения этой ячейки нужен доступ к интернету.

In [9]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

r = requests.get(url, verify=False)
    data = StringIO(r.text)

df = pd.read_csv(data)
df.head()

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


### 2.3.3. Выполнить с датафреймом действия из примеров 2.2.5–2.2.7

In [12]:
print("Первые 5 строк:")
print(df.head())

print("\nПоследние 5 строк:")
print(df.tail())

print("\nРазмерность датафрейма:")
print(df.shape)

print("\nОписательная статистика:")
print(df.describe(include="all"))

print("\nВыбор отдельных столбцов:")
print(df[["sepal_length", "sepal_width", "species"]].head())

print("\nСрез строк с 5 по 10:")
print(df.iloc[5:11])

print("\nСтроки, где длина чашелистика больше 5:")
print(df[df["sepal_length"] > 5].head())

print("\nСтроки, где вид 'setosa' и ширина чашелистика больше 3:")
print(df[(df["species"] == "setosa") & (df["sepal_width"] > 3)].head())

Первые 5 строк:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Последние 5 строк:
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

Размерность датафрейма:
(150, 5)

Описательная статистика:
        sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    

## 3. Нормализация данных

### 3.3.2. Нормализация признаков набора iris

Для выполнения этой ячейки нужен доступ к интернету, так как набор данных загружается по ссылке из задания.

In [18]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"

r = requests.get(url, verify=False)
data = StringIO(r.text)
iris = pd.read_csv(data)

minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

iris["sepal_length_cm_minmax"] = minmax_scaler.fit_transform(iris[["sepal_length_cm"]])
iris["sepal_width_cm_zscore"] = standard_scaler.fit_transform(iris[["sepal_width_cm"]])

print(iris[[
    "sepal_length_cm",
    "sepal_length_cm_minmax",
    "sepal_width_cm",
    "sepal_width_cm_zscore"
]].head(10))

   sepal_length_cm  sepal_length_cm_minmax  sepal_width_cm  \
0              5.1                0.222222             3.5   
1              4.9                0.166667             3.0   
2              4.7                0.111111             3.2   
3              4.6                0.083333             3.1   
4              5.0                0.194444             3.6   
5              5.4                0.305556             3.9   
6              4.6                0.083333             3.4   
7              5.0                0.194444             3.4   
8              4.4                0.027778             2.9   
9              4.9                0.166667             3.1   

   sepal_width_cm_zscore  
0               1.032057  
1              -0.124958  
2               0.337848  
3               0.106445  
4               1.263460  
5               1.957669  
6               0.800654  
7               0.800654  
8              -0.356361  
9               0.106445  


/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
